"""Explicit dependency surface shared by explorer tab renderers."""

from __future__ import annotations

import hashlib
import json
import os
from collections import defaultdict
from pathlib import Path

from attention_maps.eda.contracts import (
    AnalysisConfig as EDAAnalysisConfig,
    SurveyPlan as EDASurveyPlan,
    SurveyRun as EDASurveyRun,
)
from attention_maps.eda.pipeline import analyze_records as analyze_eda_records
from attention_maps.eda.reporting import write_survey_report
from attention_maps.eda.sampling import fold_seed, plan_repeated_sampling
from attention_maps.evaluation.flores import (
    FLORES_DATASET_ID,
    FLORES_SPLIT_SIZES,
    FLORES_TRANSLATION_PROMPT,
    FloresEvaluationError,
    score_flores_results,
)
from attention_maps.evaluation.nlue import (
    DECODER_EVALUATION_TASKS,
    NLUE_COLLECTION_URL,
    NLUE_PAPER_URL,
    NLUEEvaluationError,
    published_baseline_rows,
    score_nlue_results,
)
from attention_maps.explorer import (
    ARKIOS_BACKEND_NAME,
    DEFAULT_DATA_ROOT,
    DEFAULT_EDA_TERMS,
    ENGLISH_WORDCLOUD_STOPWORDS,
    GEMMA4_BASE_BACKEND_NAME,
    GOOGLE_GEMMA_BACKEND_NAME,
    HIMALAYAGPT_BACKEND_NAME,
    VIEWER_PREFIX,
    configured_eda_output_root,
    configured_finetuned_models_root,
    create_wordcloud,
    default_columns,
    eda_dataset_spec,
    extract_text,
    find_devanagari_font,
    find_latin_font,
    find_manifest,
    font_supports_devanagari,
    load_eda_cleaning_notes,
    parse_eda_terms,
    parse_model_ids,
    parse_number_list,
    parse_stopwords,
    preview_records,
    render_full_record,
    sample_dataset_rows,
    secret_fingerprint,
    sentiment_column,
    sentiment_label,
    sentiment_prediction,
    split_human_assistant_example,
    text_columns,
    word_frequencies,
)
from attention_maps.inference.arkios import (
    DEFAULT_ARKIOS_MODEL_ID,
    DEFAULT_ARKIOS_REVISION,
    ArkiosBackend,
)
from attention_maps.inference.comparison import (
    DEFAULT_GEMINI_FLASH_LITE_MODEL,
    DEFAULT_GEMINI_MODEL,
    DEFAULT_GOOGLE_GEMMA_MODEL,
    ComparisonConfigurationError,
    DecodingConfig,
    LocalPeftBackend,
    build_decoding_grid,
    build_prompt,
    comparison_csv,
    run_comparison,
)
from attention_maps.inference.gemma4_base import (
    DEFAULT_GEMMA4_BASE_MODEL_ID,
    DEFAULT_GEMMA4_BASE_REVISION,
    Gemma4BaseBackend,
)
from attention_maps.inference.gemini_translation import (
    LIMA_TEACHER_MODEL,
    LIMA_TEACHER_TEMPERATURE,
    LIMA_TEACHER_TOP_K,
    LIMA_TEACHER_TOP_P,
)
from attention_maps.inference.himalayagpt import (
    DEFAULT_HIMALAYAGPT_MODEL_ID,
    DEFAULT_HIMALAYAGPT_REVISION,
    HimalayaGPTBackend,
)
from attention_maps.inference.iriis_gpt2 import (
    IRIIS_GPT2_BACKEND_OPTIONS,
    IRIISGPT2Backend,
)
from attention_maps.inference.local_comparison import (
    LOCAL_QUANTIZATION_CHOICES,
    LocalAdapterSpec,
    LocalInferenceError,
    build_local_decoding_grid,
    discover_local_adapters,
    local_comparison_csv,
    local_model_context_limit,
    run_local_comparison,
)
from attention_maps.tokenization.analysis import (
    TokenizerAnalysisError,
    TokenizerSpec,
    analyses_csv,
    analyze_tokenizer,
    tokenizer_specs,
)


__all__ = [
    "ARKIOS_BACKEND_NAME",
    "ArkiosBackend",
    "ComparisonConfigurationError",
    "DECODER_EVALUATION_TASKS",
    "DEFAULT_ARKIOS_MODEL_ID",
    "DEFAULT_ARKIOS_REVISION",
    "DEFAULT_DATA_ROOT",
    "DEFAULT_EDA_TERMS",
    "DEFAULT_GEMINI_FLASH_LITE_MODEL",
    "DEFAULT_GEMINI_MODEL",
    "DEFAULT_GEMMA4_BASE_MODEL_ID",
    "DEFAULT_GEMMA4_BASE_REVISION",
    "DEFAULT_GOOGLE_GEMMA_MODEL",
    "DEFAULT_HIMALAYAGPT_MODEL_ID",
    "DEFAULT_HIMALAYAGPT_REVISION",
    "DecodingConfig",
    "EDAAnalysisConfig",
    "EDASurveyPlan",
    "EDASurveyRun",
    "ENGLISH_WORDCLOUD_STOPWORDS",
    "FLORES_DATASET_ID",
    "FLORES_SPLIT_SIZES",
    "FLORES_TRANSLATION_PROMPT",
    "FloresEvaluationError",
    "GEMMA4_BASE_BACKEND_NAME",
    "GOOGLE_GEMMA_BACKEND_NAME",
    "Gemma4BaseBackend",
    "HIMALAYAGPT_BACKEND_NAME",
    "HimalayaGPTBackend",
    "IRIISGPT2Backend",
    "IRIIS_GPT2_BACKEND_OPTIONS",
    "LIMA_TEACHER_MODEL",
    "LIMA_TEACHER_TEMPERATURE",
    "LIMA_TEACHER_TOP_K",
    "LIMA_TEACHER_TOP_P",
    "LOCAL_QUANTIZATION_CHOICES",
    "LocalAdapterSpec",
    "LocalInferenceError",
    "LocalPeftBackend",
    "NLUEEvaluationError",
    "NLUE_COLLECTION_URL",
    "NLUE_PAPER_URL",
    "Path",
    "TokenizerAnalysisError",
    "TokenizerSpec",
    "VIEWER_PREFIX",
    "analyses_csv",
    "analyze_eda_records",
    "analyze_tokenizer",
    "build_decoding_grid",
    "build_local_decoding_grid",
    "build_prompt",
    "comparison_csv",
    "configured_eda_output_root",
    "configured_finetuned_models_root",
    "create_wordcloud",
    "default_columns",
    "defaultdict",
    "discover_local_adapters",
    "eda_dataset_spec",
    "extract_text",
    "find_devanagari_font",
    "find_latin_font",
    "find_manifest",
    "fold_seed",
    "font_supports_devanagari",
    "hashlib",
    "json",
    "load_eda_cleaning_notes",
    "local_comparison_csv",
    "local_model_context_limit",
    "os",
    "parse_eda_terms",
    "parse_model_ids",
    "parse_number_list",
    "parse_stopwords",
    "plan_repeated_sampling",
    "preview_records",
    "published_baseline_rows",
    "render_full_record",
    "run_comparison",
    "run_local_comparison",
    "sample_dataset_rows",
    "score_flores_results",
    "score_nlue_results",
    "secret_fingerprint",
    "sentiment_column",
    "sentiment_label",
    "sentiment_prediction",
    "split_human_assistant_example",
    "text_columns",
    "tokenizer_specs",
    "word_frequencies",
    "write_survey_report",
]
